local ci = {}
local cg = {}
local rep = {}
local has = bbq.has
local check_item_exists = bbq.util.check_item_exists
local check_group_exists = bbq.util.check_group_exists

cg.stick = check_group_exists("group:stick")
cg.torch = check_group_exists("group:torch")
cg.wood = check_group_exists("group:wood")

-- this is from a dump, we don't use all of these
cg.food_apple = check_group_exists("group:food_apple")
cg.food_artichoke = check_group_exists("group:food_artichoke")
cg.food_asparagus = check_group_exists("group:food_asparagus")
cg.food_bacon = check_group_exists("group:food_bacon")
cg.food_bacon_raw = check_group_exists("group:food_bacon_raw")
cg.food_baking_tray = check_group_exists("group:food_baking_tray")
cg.food_bamboo_sprout = check_group_exists("group:food_bamboo_sprout")
cg.food_banana = check_group_exists("group:food_banana")
cg.food_barley = check_group_exists("group:food_barley")
cg.food_beans = check_group_exists("group:food_beans")
cg.food_beef = check_group_exists("group:food_beef")
cg.food_beef_raw = check_group_exists("group:food_beef_raw")
cg.food_beetroot = check_group_exists("group:food_beetroot")
cg.food_berry = check_group_exists("group:food_berry")
cg.food_big_sandwich = check_group_exists("group:food_big_sandwich")
cg.food_bird = check_group_exists("group:food_bird")
cg.food_blackberries = check_group_exists("group:food_blackberries")
cg.food_blackberry = check_group_exists("group:food_blackberry")
cg.food_blueberries = check_group_exists("group:food_blueberries")
cg.food_blueberry = check_group_exists("group:food_blueberry")
cg.food_blueberry_jam = check_group_exists("group:food_blueberry_jam")
cg.food_bowl = check_group_exists("group:food_bowl")
cg.food_brandy = check_group_exists("group:food_brandy")
cg.food_bread = check_group_exists("group:food_bread")
cg.food_bread_crumbs = check_group_exists("group:food_bread_crumbs")
cg.food_bread_slice = check_group_exists("group:food_bread_slice")
cg.food_butter = check_group_exists("group:food_butter")
cg.food_cabbage = check_group_exists("group:food_cabbage")
cg.food_candied = check_group_exists("group:food_candied")
cg.food_candied_lemon = check_group_exists("group:food_candied_lemon")
cg.food_carrot = check_group_exists("group:food_carrot")
cg.food_cheese = check_group_exists("group:food_cheese")
cg.food_chicken = check_group_exists("group:food_chicken")
cg.food_chicken_raw = check_group_exists("group:food_chicken_raw")
cg.food_chicken_strips = check_group_exists("group:food_chicken_strips")
cg.food_chili_pepper = check_group_exists("group:food_chili_pepper")
cg.food_chives = check_group_exists("group:food_chives")
cg.food_chocolate = check_group_exists("group:food_chocolate")
cg.food_chocolate_dark = check_group_exists("group:food_chocolate_dark")
cg.food_cocoa = check_group_exists("group:food_cocoa")
cg.food_coconut = check_group_exists("group:food_coconut")
cg.food_coconut_slice = check_group_exists("group:food_coconut_slice")
cg.food_coffee = check_group_exists("group:food_coffee")
cg.food_cookie = check_group_exists("group:food_cookie")
cg.food_corn = check_group_exists("group:food_corn")
cg.food_corn_cooked = check_group_exists("group:food_corn_cooked")
cg.food_corn_flour = check_group_exists("group:food_corn_flour") or (bbq.has.yl_seasons and "group:food_corn_flour")
cg.food_cornstarch = check_group_exists("group:food_cornstarch")
cg.food_cucumber = check_group_exists("group:food_cucumber")
cg.food_cutting_board = check_group_exists("group:food_cutting_board")
cg.food_egg = check_group_exists("group:food_egg")
cg.food_egg_fried = check_group_exists("group:food_egg_fried")
cg.food_fish = check_group_exists("group:food_fish")
cg.food_fish_raw = check_group_exists("group:food_fish_raw")
cg.food_flour = check_group_exists("group:food_flour")
cg.food_garlic = check_group_exists("group:food_garlic")
cg.food_garlic_clove = check_group_exists("group:food_garlic_clove")
cg.food_gelatin = check_group_exists("group:food_gelatin")
cg.food_goat = check_group_exists("group:food_goat")
cg.food_goat_raw = check_group_exists("group:food_goat_raw")
cg.food_gooseberry = check_group_exists("group:food_gooseberry")
cg.food_grains = check_group_exists("group:food_grains")
cg.food_grapes = check_group_exists("group:food_grapes")
cg.food_ham = check_group_exists("group:food_ham")
cg.food_honey = check_group_exists("group:food_honey")
cg.food_hot = check_group_exists("group:food_hot")
cg.food_icecream = check_group_exists("group:food_icecream")
cg.food_jam = check_group_exists("group:food_jam")
cg.food_juicer = check_group_exists("group:food_juicer")
cg.food_kohlrabi = check_group_exists("group:food_kohlrabi")
cg.food_lemon = check_group_exists("group:food_lemon")
cg.food_lettuce = check_group_exists("group:food_lettuce")
cg.food_meat = check_group_exists("group:food_meat")
cg.food_meat_raw = check_group_exists("group:food_meat_raw")
cg.food_melon = check_group_exists("group:food_melon")
cg.food_melon_slice = check_group_exists("group:food_melon_slice")
cg.food_milk = check_group_exists("group:food_milk")
cg.food_milk_glass = check_group_exists("group:food_milk_glass")
cg.food_mint = check_group_exists("group:food_mint")
cg.food_molasses = check_group_exists("group:food_molasses")
cg.food_mortar_pestle = check_group_exists("group:food_mortar_pestle")
cg.food_mushroom = check_group_exists("group:food_mushroom")
cg.food_mutton = check_group_exists("group:food_mutton")
cg.food_mutton_raw = check_group_exists("group:food_mutton_raw")
cg.food_nut = check_group_exists("group:food_nut")
cg.food_nutella = check_group_exists("group:food_nutella")
cg.food_oat = check_group_exists("group:food_oat")
cg.food_oats = check_group_exists("group:food_oats")
cg.food_oil = check_group_exists("group:food_oil")
cg.food_olive_oil = check_group_exists("group:food_olive_oil")
cg.food_onion = check_group_exists("group:food_onion")
cg.food_orange = check_group_exists("group:food_orange")
cg.food_parsley = check_group_exists("group:food_parsley")
cg.food_pasta = check_group_exists("group:food_pasta")
cg.food_pea_pod = check_group_exists("group:food_pea_pod")
cg.food_peanut = check_group_exists("group:food_peanut")
cg.food_peanut_butter = check_group_exists("group:food_peanut_butter")
cg.food_peanuts = check_group_exists("group:food_peanuts")
cg.food_peas = check_group_exists("group:food_peas")
cg.food_pepper = check_group_exists("group:food_pepper")
cg.food_pepper_ground = check_group_exists("group:food_pepper_ground")
cg.food_peppercorn = check_group_exists("group:food_peppercorn")
cg.food_pine_nuts = check_group_exists("group:food_pine_nuts")
cg.food_pineapple = check_group_exists("group:food_pineapple")
cg.food_pineapple_ring = check_group_exists("group:food_pineapple_ring")
cg.food_plate = check_group_exists("group:food_plate")
cg.food_popcorn = check_group_exists("group:food_popcorn")
cg.food_pork = check_group_exists("group:food_pork")
cg.food_pork_raw = check_group_exists("group:food_pork_raw")
cg.food_pot = check_group_exists("group:food_pot")
cg.food_potato = check_group_exists("group:food_potato")
cg.food_pumpkin = check_group_exists("group:food_pumpkin")
cg.food_pumpkin_slice = check_group_exists("group:food_pumpkin_slice")
cg.food_rabbit = check_group_exists("group:food_rabbit")
cg.food_rabbit_raw = check_group_exists("group:food_rabbit_raw")
cg.food_raspberries = check_group_exists("group:food_raspberries")
cg.food_raspberry = check_group_exists("group:food_raspberry")
cg.food_rat = check_group_exists("group:food_rat")
cg.food_rhubarb = check_group_exists("group:food_rhubarb")
cg.food_rice = check_group_exists("group:food_rice")
cg.food_rice_bread = check_group_exists("group:food_rice_bread")
cg.food_rice_flour = check_group_exists("group:food_rice_flour")
cg.food_rose_water = check_group_exists("group:food_rose_water")
cg.food_rosemary = check_group_exists("group:food_rosemary")
cg.food_rye = check_group_exists("group:food_rye")
cg.food_salt = check_group_exists("group:food_salt")
cg.food_sandwich = check_group_exists("group:food_sandwich")
cg.food_sauce = check_group_exists("group:food_sauce")
cg.food_saucepan = check_group_exists("group:food_saucepan")
cg.food_seaweed = check_group_exists("group:food_seaweed")
cg.food_skillet = check_group_exists("group:food_skillet")
cg.food_soup = check_group_exists("group:food_soup")
cg.food_soy = check_group_exists("group:food_soy")
cg.food_soy_pod = check_group_exists("group:food_soy_pod")
cg.food_soy_sauce = check_group_exists("group:food_soy_sauce")
cg.food_spicy = check_group_exists("group:food_spicy")
cg.food_starch = check_group_exists("group:food_starch")
cg.food_strawberry = check_group_exists("group:food_strawberry")
cg.food_sugar = check_group_exists("group:food_sugar")
cg.food_sunflower = check_group_exists("group:food_sunflower")
cg.food_sunflower_seeds = check_group_exists("group:food_sunflower_seeds")
cg.food_sunflower_seeds_toasted = check_group_exists("group:food_sunflower_seeds_toasted")
cg.food_sweet = check_group_exists("group:food_sweet")
cg.food_sweet_bread = check_group_exists("group:food_sweet_bread")
cg.food_toast = check_group_exists("group:food_toast")
cg.food_tofu = check_group_exists("group:food_tofu")
cg.food_tofu_raw = check_group_exists("group:food_tofu_raw")
cg.food_tomato = check_group_exists("group:food_tomato")
cg.food_tomato_sauce = check_group_exists("group:food_tomato_sauce")
cg.food_tuber = check_group_exists("group:food_tuber")
cg.food_vanilla = check_group_exists("group:food_vanilla")
cg.food_vegan = check_group_exists("group:food_vegan")
cg.food_vegan_meat = check_group_exists("group:food_vegan_meat")
cg.food_vegan_sandwich = check_group_exists("group:food_vegan_sandwich")
cg.food_water_glass = check_group_exists("group:food_water_glass")
cg.food_wheat = check_group_exists("group:food_wheat")
cg.food_wine = check_group_exists("group:food_wine")

cg.food_pizza_dough = check_group_exists("group:pizza_dough") -- it's not food_pizza_dough

cg.food_bread_slice = cg.food_bread_slice or cg.food_bread
cg.food_bread_crumbs = cg.food_bread_crumbs or cg.food_bread_slice
cg.food_toast = cg.food_toast or cg.food_bread_slice
cg.food_pizza_dough = cg.food_pizza_dough or cg.food_flour

if has.bucket then
	ci.bucket_empty = check_item_exists("bucket:bucket_empty")
	ci.bucket_water = check_item_exists("bucket:bucket_water")
	rep.bucket_water = check_item_exists("bucket:bucket_empty")
end

if has.default then
	ci.tin = check_item_exists("default:tin_ingot")
end

if has.farming then
	ci.cotton = check_item_exists("farming:cotton")
	ci.cotton_seed = check_item_exists("farming:seed_cotton")

	rep.food_baking_tray = check_item_exists("farming:baking_tray")
	rep.food_bowl = check_item_exists("farming:bowl")
	rep.food_cutting_board = check_item_exists("farming:cutting_board")
	rep.food_juicer = check_item_exists("farming:juicer")
	rep.food_mixing_bowl = check_item_exists("farming:mixing_bowl")
	rep.food_mortar_pestle = check_item_exists("farming:mortar_pestle")
	rep.food_pot = check_item_exists("farming:pot")
	rep.food_saucepan = check_item_exists("farming:saucepan")
	rep.food_skillet = check_item_exists("farming:skillet")
end

if has.sandwiches then
	ci.caramelized_onion = check_item_exists("sandwiches:caramelized_onion")
end

if not ci.caramelized_onion then
	ci.caramelized_onion = cg.food_onion
end

if has.vessels then
	ci.bottle_empty = check_item_exists("vessels:glass_bottle")
	ci.glass_empty = check_item_exists("vessels:drinking_glass")

	rep.food_milk_glass = check_item_exists("vessels:drinking_glass")
	rep.food_water_glass = check_item_exists("vessels:drinking_glass")
	rep.food_oil = check_item_exists("vessels:glass_bottle")
	rep.food_pepper_ground = check_item_exists("vessels:glass_bottle")
	rep.food_molasses = check_item_exists("vessels:glass_bottle")
	rep.food_tomato_sauce = check_item_exists("vessels:drinking_glass")
	rep.food_salt = check_item_exists("vessels:glass_bottle")
end

bbq.resources.craftitems = ci
bbq.resources.craftgroups = cg
bbq.resources.replacements = rep
